/* tslint:disable */
/* eslint-disable */
/**
 * Tech-Inventory API
 * Rest API of TECH-INVENTORY
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ObyektDTO,
    ObyektDTOFromJSON,
    ObyektDTOFromJSONTyped,
    ObyektDTOToJSON,
} from './ObyektDTO';

/**
 * 
 * @export
 * @interface AttachmentDTO
 */
export interface AttachmentDTO {
    /**
     * 
     * @type {number}
     * @memberof AttachmentDTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof AttachmentDTO
     */
    path?: string;
    /**
     * 
     * @type {string}
     * @memberof AttachmentDTO
     */
    originalFileName?: string;
    /**
     * 
     * @type {string}
     * @memberof AttachmentDTO
     */
    fileName?: string;
    /**
     * 
     * @type {string}
     * @memberof AttachmentDTO
     */
    contentType?: string;
    /**
     * 
     * @type {string}
     * @memberof AttachmentDTO
     */
    fileSize?: string;
    /**
     * 
     * @type {string}
     * @memberof AttachmentDTO
     */
    info?: string;
    /**
     * 
     * @type {ObyektDTO}
     * @memberof AttachmentDTO
     */
    obyekt?: ObyektDTO;
}


export function AttachmentDTOFromJSON(json: any): AttachmentDTO {
    return AttachmentDTOFromJSONTyped(json, false);
}

export function AttachmentDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttachmentDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'path': !exists(json, 'path') ? undefined : json['path'],
        'originalFileName': !exists(json, 'originalFileName') ? undefined : json['originalFileName'],
        'fileName': !exists(json, 'fileName') ? undefined : json['fileName'],
        'contentType': !exists(json, 'contentType') ? undefined : json['contentType'],
        'fileSize': !exists(json, 'fileSize') ? undefined : json['fileSize'],
        'info': !exists(json, 'info') ? undefined : json['info'],
        'obyekt': !exists(json, 'obyekt') ? undefined : ObyektDTOFromJSON(json['obyekt']),
    };
}

export function AttachmentDTOToJSON(value?: AttachmentDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'path': value.path,
        'originalFileName': value.originalFileName,
        'fileName': value.fileName,
        'contentType': value.contentType,
        'fileSize': value.fileSize,
        'info': value.info,
        'obyekt': ObyektDTOToJSON(value.obyekt),
    };
}

