/* tslint:disable */
/* eslint-disable */
/**
 * Tech-Inventory API
 * Rest API of TECH-INVENTORY
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LoyihaDTO,
    LoyihaDTOFromJSON,
    LoyihaDTOFromJSONTyped,
    LoyihaDTOToJSON,
} from './LoyihaDTO';

/**
 * 
 * @export
 * @interface BuyurtmaRaqamDTO
 */
export interface BuyurtmaRaqamDTO {
    /**
     * 
     * @type {number}
     * @memberof BuyurtmaRaqamDTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof BuyurtmaRaqamDTO
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof BuyurtmaRaqamDTO
     */
    numberOfOrder?: string;
    /**
     * 
     * @type {LoyihaDTO}
     * @memberof BuyurtmaRaqamDTO
     */
    loyiha?: LoyihaDTO;
}


export function BuyurtmaRaqamDTOFromJSON(json: any): BuyurtmaRaqamDTO {
    return BuyurtmaRaqamDTOFromJSONTyped(json, false);
}

export function BuyurtmaRaqamDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): BuyurtmaRaqamDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'numberOfOrder': !exists(json, 'numberOfOrder') ? undefined : json['numberOfOrder'],
        'loyiha': !exists(json, 'loyiha') ? undefined : LoyihaDTOFromJSON(json['loyiha']),
    };
}

export function BuyurtmaRaqamDTOToJSON(value?: BuyurtmaRaqamDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'numberOfOrder': value.numberOfOrder,
        'loyiha': LoyihaDTOToJSON(value.loyiha),
    };
}

