/* tslint:disable */
/* eslint-disable */
/**
 * Tech-Inventory API
 * Rest API of TECH-INVENTORY
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CabelTypeDTO,
    CabelTypeDTOFromJSON,
    CabelTypeDTOFromJSONTyped,
    CabelTypeDTOToJSON,
} from './CabelTypeDTO';

/**
 * 
 * @export
 * @interface CabelDTO
 */
export interface CabelDTO {
    /**
     * 
     * @type {number}
     * @memberof CabelDTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof CabelDTO
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CabelDTO
     */
    model?: string;
    /**
     * 
     * @type {string}
     * @memberof CabelDTO
     */
    info?: string;
    /**
     * 
     * @type {CabelTypeDTO}
     * @memberof CabelDTO
     */
    cabelType?: CabelTypeDTO;
}


export function CabelDTOFromJSON(json: any): CabelDTO {
    return CabelDTOFromJSONTyped(json, false);
}

export function CabelDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CabelDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'model': !exists(json, 'model') ? undefined : json['model'],
        'info': !exists(json, 'info') ? undefined : json['info'],
        'cabelType': !exists(json, 'cabelType') ? undefined : CabelTypeDTOFromJSON(json['cabelType']),
    };
}

export function CabelDTOToJSON(value?: CabelDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'model': value.model,
        'info': value.info,
        'cabelType': CabelTypeDTOToJSON(value.cabelType),
    };
}

