/* tslint:disable */
/* eslint-disable */
/**
 * Tech-Inventory API
 * Rest API of TECH-INVENTORY
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Camera brendi
 * @export
 * @interface CameraBrandDTO
 */
export interface CameraBrandDTO {
    /**
     * 
     * @type {number}
     * @memberof CameraBrandDTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof CameraBrandDTO
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CameraBrandDTO
     */
    info?: string;
}


export function CameraBrandDTOFromJSON(json: any): CameraBrandDTO {
    return CameraBrandDTOFromJSONTyped(json, false);
}

export function CameraBrandDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CameraBrandDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': json['name'],
        'info': !exists(json, 'info') ? undefined : json['info'],
    };
}

export function CameraBrandDTOToJSON(value?: CameraBrandDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'info': value.info,
    };
}

