/* tslint:disable */
/* eslint-disable */
/**
 * Tech-Inventory API
 * Rest API of TECH-INVENTORY
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    RegionDTO,
    RegionDTOFromJSON,
    RegionDTOFromJSONTyped,
    RegionDTOToJSON,
} from './RegionDTO';

/**
 * Район-Tuman.
 * @export
 * @interface DistrictDTO
 */
export interface DistrictDTO {
    /**
     * 
     * @type {number}
     * @memberof DistrictDTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof DistrictDTO
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof DistrictDTO
     */
    info?: string;
    /**
     * 
     * @type {RegionDTO}
     * @memberof DistrictDTO
     */
    region?: RegionDTO;
}


export function DistrictDTOFromJSON(json: any): DistrictDTO {
    return DistrictDTOFromJSONTyped(json, false);
}

export function DistrictDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): DistrictDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': json['name'],
        'info': !exists(json, 'info') ? undefined : json['info'],
        'region': !exists(json, 'region') ? undefined : RegionDTOFromJSON(json['region']),
    };
}

export function DistrictDTOToJSON(value?: DistrictDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'info': value.info,
        'region': RegionDTOToJSON(value.region),
    };
}

