/* tslint:disable */
/* eslint-disable */
/**
 * Tech-Inventory API
 * Rest API of TECH-INVENTORY
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ObjectTasnifiTuriDTO,
    ObjectTasnifiTuriDTOFromJSON,
    ObjectTasnifiTuriDTOFromJSONTyped,
    ObjectTasnifiTuriDTOToJSON,
} from './ObjectTasnifiTuriDTO';

/**
 * Object tasnifi
 * @export
 * @interface ObjectTasnifiDTO
 */
export interface ObjectTasnifiDTO {
    /**
     * 
     * @type {number}
     * @memberof ObjectTasnifiDTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ObjectTasnifiDTO
     */
    name: string;
    /**
     * 
     * @type {ObjectTasnifiTuriDTO}
     * @memberof ObjectTasnifiDTO
     */
    bjectTasnifiTuri?: ObjectTasnifiTuriDTO;
}


export function ObjectTasnifiDTOFromJSON(json: any): ObjectTasnifiDTO {
    return ObjectTasnifiDTOFromJSONTyped(json, false);
}

export function ObjectTasnifiDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ObjectTasnifiDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': json['name'],
        'bjectTasnifiTuri': !exists(json, 'bjectTasnifiTuri') ? undefined : ObjectTasnifiTuriDTOFromJSON(json['bjectTasnifiTuri']),
    };
}

export function ObjectTasnifiDTOToJSON(value?: ObjectTasnifiDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'bjectTasnifiTuri': ObjectTasnifiTuriDTOToJSON(value.bjectTasnifiTuri),
    };
}

