/* tslint:disable */
/* eslint-disable */
/**
 * Tech-Inventory API
 * Rest API of TECH-INVENTORY
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Object tasnifi turi
 * @export
 * @interface ObjectTasnifiTuriDTO
 */
export interface ObjectTasnifiTuriDTO {
    /**
     * 
     * @type {number}
     * @memberof ObjectTasnifiTuriDTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ObjectTasnifiTuriDTO
     */
    name: string;
}


export function ObjectTasnifiTuriDTOFromJSON(json: any): ObjectTasnifiTuriDTO {
    return ObjectTasnifiTuriDTOFromJSONTyped(json, false);
}

export function ObjectTasnifiTuriDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ObjectTasnifiTuriDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': json['name'],
    };
}

export function ObjectTasnifiTuriDTOToJSON(value?: ObjectTasnifiTuriDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
    };
}

