/* tslint:disable */
/* eslint-disable */
/**
 * Tech-Inventory API
 * Rest API of TECH-INVENTORY
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    BuyurtmaRaqamDTO,
    BuyurtmaRaqamDTOFromJSON,
    BuyurtmaRaqamDTOFromJSONTyped,
    BuyurtmaRaqamDTOToJSON,
} from './BuyurtmaRaqamDTO';

/**
 * Локация - полный адресс.
 * @export
 * @interface ObyektDTO
 */
export interface ObyektDTO {
    /**
     * 
     * @type {number}
     * @memberof ObyektDTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ObyektDTO
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ObyektDTO
     */
    home?: string;
    /**
     * 
     * @type {string}
     * @memberof ObyektDTO
     */
    street?: string;
    /**
     * 
     * @type {string}
     * @memberof ObyektDTO
     */
    latitude?: string;
    /**
     * 
     * @type {string}
     * @memberof ObyektDTO
     */
    longitude?: string;
    /**
     * 
     * @type {string}
     * @memberof ObyektDTO
     */
    info?: string;
    /**
     * 
     * @type {BuyurtmaRaqamDTO}
     * @memberof ObyektDTO
     */
    buyurtmaRaqam?: BuyurtmaRaqamDTO;
}


export function ObyektDTOFromJSON(json: any): ObyektDTO {
    return ObyektDTOFromJSONTyped(json, false);
}

export function ObyektDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ObyektDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': json['name'],
        'home': !exists(json, 'home') ? undefined : json['home'],
        'street': !exists(json, 'street') ? undefined : json['street'],
        'latitude': !exists(json, 'latitude') ? undefined : json['latitude'],
        'longitude': !exists(json, 'longitude') ? undefined : json['longitude'],
        'info': !exists(json, 'info') ? undefined : json['info'],
        'buyurtmaRaqam': !exists(json, 'buyurtmaRaqam') ? undefined : BuyurtmaRaqamDTOFromJSON(json['buyurtmaRaqam']),
    };
}

export function ObyektDTOToJSON(value?: ObyektDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'home': value.home,
        'street': value.street,
        'latitude': value.latitude,
        'longitude': value.longitude,
        'info': value.info,
        'buyurtmaRaqam': BuyurtmaRaqamDTOToJSON(value.buyurtmaRaqam),
    };
}

